sudo: required
language: c++
compiler: clang

services:
  - docker

os: linux
addons:
  sonarcloud:
    organization: "kikawet"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-7-dev
    - libboost-all-dev

before_install:
    docker build --pull --rm -f "Docker\Dockerfile" -t kikawet/pifromcoprimes:latest .

script:
  - make clean
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output make all
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner
  - if [ "$TRAVIS_BRANCH" == "travis" ]; then
      docker images kikawet/pifromcoprimes:latest
    fi

after_success:
  - if [ "$TRAVIS_BRANCH" == "travis" ]; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push cinhtau/elasticsearch;
    fi

cache:
  directories:
    - '$HOME/.sonar/cache'
